import { useState, useEffect } from 'react';
import { User } from 'firebase/auth';
import { getUserConcepts, NovelConcept } from '../lib/firebase';
import { Loader2, Calendar, FileText, Download } from 'lucide-react';
import { motion } from 'motion/react';
import ReactMarkdown from 'react-markdown';
import { GenreChart } from './GenreChart';
import { exportToPDF } from '../lib/pdf';

export function HistoryView({ user }: { user: User }) {
  const [concepts, setConcepts] = useState<NovelConcept[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [printId, setPrintId] = useState<string | null>(null);

  useEffect(() => {
    const fetchConcepts = async () => {
      try {
        const data = await getUserConcepts(user.uid);
        setConcepts(data);
      } catch (err) {
        setError('Failed to load history');
      } finally {
        setLoading(false);
      }
    };
    fetchConcepts();
  }, [user.uid]);

  const handleExportPDF = async (concept: NovelConcept, elementId: string) => {
    const element = document.getElementById(elementId);
    if (!element) return;
    
    try {
      await exportToPDF(
        element,
        `Concept-${concept.theme.substring(0, 20).replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`
      );
    } catch (err) {
      console.error('PDF generation failed', err);
      setError('Failed to export PDF');
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center py-20">
        <Loader2 className="h-8 w-8 text-[#1a1a1a] animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 text-[10px] uppercase tracking-widest font-bold text-red-600 bg-red-50 border border-red-200">
        {error}
      </div>
    );
  }

  if (concepts.length === 0) {
    return (
      <div className="text-center py-32 bg-white border border-[#1a1a1a]">
        <div className="mx-auto w-12 h-12 border border-[#1a1a1a] rounded-full flex items-center justify-center mb-6 bg-[#f9f9f9]">
          <FileText className="h-5 w-5 text-gray-400" />
        </div>
        <h3 className="text-[10px] uppercase tracking-[0.2em] font-bold text-[#1a1a1a] mb-2">Archive Empty</h3>
        <p className="text-xs font-serif italic text-gray-500">Generate your first novel concept to populate the archive.</p>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <h2 className="text-[10px] uppercase tracking-[0.2em] font-bold text-gray-400 print:hidden">Concept Archive</h2>
      
      <div className="print:hidden">
        <GenreChart concepts={concepts} />
      </div>

      <div className="grid gap-8 print:block print:space-y-8">
        {concepts.map((concept, index) => (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            key={concept.id}
            className={`bg-white border-l-[4px] border-[#1a1a1a] border-y border-r border-gray-100 p-8 flex flex-col gap-6 print:border-none print:p-0 print:mb-8 print:break-inside-avoid ${printId && printId !== concept.id ? 'print:hidden' : ''}`}
          >
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
              <div className="flex-1 print:block">
                <div className="flex items-center gap-3 text-[9px] uppercase tracking-widest font-bold text-gray-400 mb-3">
                  <span className="text-[#1a1a1a]">{concept.createdAt?.toDate().toLocaleDateString() || 'Recently'}</span>
                  <span className="w-1 h-1 bg-gray-300 rounded-full print:hidden"></span>
                  <span className="print:hidden">Generated by Gemini</span>
                </div>
                <p className="text-xl md:text-2xl font-serif italic text-[#1a1a1a] leading-tight max-w-2xl">
                  {concept.theme}
                </p>
              </div>
              <button
                onClick={() => handleExportPDF(concept, `concept-content-${concept.id}`)}
                className="flex items-center justify-center gap-2 border border-[#1a1a1a] px-4 py-2 text-[10px] uppercase tracking-widest font-bold bg-white text-[#1a1a1a] hover:bg-gray-50 transition-colors flex-shrink-0 print:hidden"
              >
                <Download className="h-3 w-3" />
                Export PDF
              </button>
            </div>
            
            <div className="pt-6 border-t border-gray-100 overflow-x-auto">
              <div id={`concept-content-${concept.id}`} className="prose prose-slate max-w-none prose-headings:font-serif prose-headings:text-[#1a1a1a] prose-p:font-serif prose-p:text-gray-700 prose-p:leading-relaxed">
                <ReactMarkdown>{concept.content}</ReactMarkdown>
                
                {concept.twists && (
                  <div className="mt-8 pt-8 border-t border-gray-200">
                    <h3 className="text-[10px] uppercase tracking-[0.4em] text-gray-400 font-bold mb-6">Plot Twists</h3>
                    <ReactMarkdown>{concept.twists}</ReactMarkdown>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
